config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

 scope module: :public do
   root to:  "homes#top"
   resources :homes, only: [:top, :about]
   resources :customers, only: [:index, :show, :edit, :update] do
    get "unsubscribe"
    patch "withdrawal"
    member do
        get :likes
    end
    resource :relationships, only: [:create, :destroy] do
        collection do
            get 'followings' => 'relationships#followings', as: 'followings'
            get 'followers' => 'relationships#followers', as: 'followers'
        end
    end
  end
   resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
       resource :likes, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end
   resources :categorys, only: [:index, :edit, :create, :update, :destroy]
   resources :chats, only: [:show, :create]
   resources :notifications, only: [:index]
 end

  namespace :admin do
    root to:"customers#index"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :update, :destroy] do
     resources :comments, only: [:index, :show, :edit, :update, :destroy]
     collection do
       get 'search'
      end
    end
    resources :categorys, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/admin/categorys_controller.rb
class Admin::CategorysController < ApplicationController

  def index
    @category = Category.new
    @categorys = Category.page(params[:page]).per(5)
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to admin_categorys_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to admin_categorys_path(@category)
  end

  def destroy
   @category = Category.find(params[:id])
   @category.destroy
   redirect_to request.referer
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/views/admin/categorys/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-5">
      <div class="card">
        <div class="card-header bg-light">
          <h5 class="mb-0"><b>カテゴリ編集</b></h5>
        </div>
        <div class="card-body">
          <%= form_with model: @category, url: admin_category_path(@category.id), method: :patch do |f| %>
            <div class="form-group">
              <%= f.label :category_name, "カテゴリ名",class: "font-weight-bold" %>
              <%= f.text_field :category_name, class: "form-control" %>
            </div>
            <%= f.submit '変更を保存', class: 'btn btn-success btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categorys/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2.5 mt-5 ml-5 mb-lg-5">
      <h5 class="h-25 bg-light">カテゴリ一覧・追加</h5>
    </div>
      <div class="col-lg-2.5 mt-5 ml-5 mb-lg-5">
      <div>
        <%= form_with model: @category, url: '/admin/categorys', method: :post, class: "form-inline" do |f| %>
          <div class="form-group">
            <%= f.label :category_name, "カテゴリ名" %>
            <%= f.text_field :category_name, class: "form-control ml-2", placeholder: "カテゴリ名" %>
          </div>
          <%= f.submit '新規登録', class: 'btn btn-success ml-3' %>
        <% end %>
      </div>
    </div>
    <div class="col-md-5 mt-4">
      <table class='table table-hover table-inverse'>
        <thead class="bg-light">
          <tr>
            <th>カテゴリ名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categorys.each do |category| %>
            <tr>
              <td><%= category.category_name %></td>
              <td><%= link_to "編集する", edit_admin_category_path(category.id), class: 'btn btn-success' %></td>
              <td><%= link_to "削除する", admin_category_path(category.id), method: :delete,  class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @categorys %>
    </div>
  </div>
</div>