config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

 scope module: :public do
   root to:  "homes#top"
   resources :homes, only: [:top, :about]
   resources :customers, only: [:index, :show, :edit, :update] do
    get "unsubscribe"
    patch "withdrawal"
    member do
        get :likes
    end
    resource :relationships, only: [:create, :destroy] do
        collection do
            get 'followings' => 'relationships#followings', as: 'followings'
            get 'followers' => 'relationships#followers', as: 'followers'
        end
    end
  end
   resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
       resource :likes, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end
   resources :categorys, only: [:index, :edit, :create, :update, :destroy]
   resources :chats, only: [:show, :create]
   resources :notifications, only: [:index]
 end

  namespace :admin do
    root to:"customers#index"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :update, :destroy] do
     resources :comments, only: [:index, :show, :edit, :update, :destroy]
     collection do
       get 'search'
      end
    end
    resources :categorys, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :customer_rooms
  has_many :chats
  has_many :rooms, through: :customer_rooms
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def likes?(post)
    likes.exists?(post: post)
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

  def follow(user_id)
     relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
   #フォロー時の通知
  def create_notification_follow!(visited_id)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",id, visited_id, 'follow'])
    if temp.blank?
      notification = active_notifications.new(
        visited_id: visited_id,
        visiter_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :introduction, :profile_image, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h3><strong><%= @customer.name %>さんの会員情報編集</strong></h3>
      <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>
        <div class="form-group">
          <%= f.label "名前" %>
          <%= f.text_field :name, class: "form-control", placeholder: "名前を入力してください" %>
        </div>
        <div class="form-group">
          <%= f.label "メールアドレス" %>
          <%= f.email_field :email, autocomplete: "email", class: "form-control", placeholder: "example@example.com" %>
        </div>
        <div class="form-group">
          <%= f.label "会員ステータス" %><br>
          <%= f.radio_button :is_deleted, :false, class: "mr-2" %>
          <%= f.label :is_deleted, "有効", class: "mr-4" %>
          <%= f.radio_button :is_deleted, :true, class: "mr-2" %>
          <%= f.label :is_deleted, "退会" %>
        </div>
        <div class="form-group">
          <%= f.submit "編集内容を保存", class: "btn btn-success btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row no-gutters">
    <div class="col-lg-12 col-xs-offset-1">
      <h2>会員一覧</h2>
      <table class="table table-bordered">
        <thead style="background-color: #f0f8ff;">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td style="background-color: #f5f5f5;"><%= customer.id %></td>
              <td class="text-dark">
              <%= link_to admin_customer_path(customer.id) do %>
                <div class="text-dark"><%= customer.name %></div>
              <% end %>
              </td>
              <td><%= customer.email %></td>
              <td><%= customer.is_deleted ? '退会' : '有効' %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 offset-md-1">
      <h3 class="mb-4">会員詳細</h3>
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><%= @customer.name %>さんの会員情報詳細</h4>
            <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
          </div>
          <ul class="list-group list-group-flush mt-4">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              会員ID
              <span class="badge badge-secondary badge-pill"><%= @customer.id %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              氏名
              <span><%= @customer.name %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              メールアドレス
              <span><%= @customer.email%></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              会員ステータス
              <span><%= @customer.is_deleted ? '退会' : '有効' %></span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>