config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

 scope module: :public do
   root to:  "homes#top"
   resources :homes, only: [:top, :about]
   resources :customers, only: [:index, :show, :edit, :update] do
    get "unsubscribe"
    patch "withdrawal"
    member do
        get :likes
    end
    resource :relationships, only: [:create, :destroy] do
        collection do
            get 'followings' => 'relationships#followings', as: 'followings'
            get 'followers' => 'relationships#followers', as: 'followers'
        end
    end
  end
   resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
       resource :likes, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end
   resources :categorys, only: [:index, :edit, :create, :update, :destroy]
   resources :chats, only: [:show, :create]
   resources :notifications, only: [:index]
 end

  namespace :admin do
    root to:"customers#index"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :update, :destroy] do
     resources :comments, only: [:index, :show, :edit, :update, :destroy]
     collection do
       get 'search'
      end
    end
    resources :categorys, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
  has_many :notifications, dependent: :destroy
  
  validates :comment, presence: true
  
  def create_notification_comment!(visiter, visited_id)
        notification = visiter.active_notifications.new(
          post_id: post_id,
          comment_id: id,
          visited_id: visited_id,
          action: 'comment'
        )
        if notification.visiter_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :customer_rooms
  has_many :chats
  has_many :rooms, through: :customer_rooms
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def likes?(post)
    likes.exists?(post: post)
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

  def follow(user_id)
     relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
   #フォロー時の通知
  def create_notification_follow!(visited_id)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",id, visited_id, 'follow'])
    if temp.blank?
      notification = active_notifications.new(
        visited_id: visited_id,
        visiter_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :post


end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}

	belongs_to :post, optional: true
  belongs_to :comment, optional: true

  # 通知
  belongs_to :visiter, class_name: 'customer', foreign_key: 'visiter_id', optional: true
	belongs_to :visited, class_name: 'customer', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 通知
  has_many :notifications, dependent: :destroy
  belongs_to :customer
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true

  scope :search_by_keyword, -> (keyword) { where("title LIKE ?", "%#{keyword}%") }

  def liked_by?(customer)
    likes&.exists?(customer_id: customer.id) if customer.present? && likes.present?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :customer_rooms
  has_many :chats
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(6)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
   @post = Post.find(params[:id])
   @post.destroy
   redirect_to request.referer
  end

  def search
    if params[:keyword].present?
      @posts = Post.search_by_keyword(params[:keyword])
    else
      @post = Post.none
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <h1>投稿一覧</h1>
  <hr>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
             <h2 class="card-title"><%= link_to post.title, admin_post_path(post) %></h2>
            <p class="card-text"><%= post.content %></p>
            <p class="card-text">いいね数: <%= post.likes.count %></p>
            <p class="card-text">コメント数: <%= post.comments.count %></p>
            <p class="card-text">投稿者: <%= link_to post.customer.name, admin_customer_path(post.customer) %></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></small>
          </div>
          <%= link_to '削除', admin_post_path(post), method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: 'btn btn-danger btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @posts %>
</div>

app/views/admin/posts/search.html.erb
<div class="container">
  <h1>検索結果</h1>
  <% if @posts.present? %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>タイトル</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= link_to post.customer.name, admin_customer_path(post.customer) %></td>
              <td><%= link_to post.title, admin_post_path(post) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>該当する投稿がありませんでした。</p>
  <% end %>
</div>

app/views/admin/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @post.title %></h1>
      <p><%= @post.content %></p>
      <p>投稿者: <%= @post.customer.name %></p>
      <p>投稿日時: <%=  @post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
    </div>
    <div class="col-md-4">
      <h2>コメント一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">投稿者</th>
            <th scope="col">コメント</th>
            <% if current_customer&.admin? %>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @post.comments.each do |comment| %>
            <tr>
              <td><%= link_to comment.customer.name,  admin_customer_path(comment.customer)%></td>
              <td><%= comment.comment %></td>
              <td>
                <%= link_to '削除', admin_post_comment_path(comment.post, comment.id), method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>