config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

 scope module: :public do
   root to:  "homes#top"
   resources :homes, only: [:top, :about]
   resources :customers, only: [:index, :show, :edit, :update] do
    get "unsubscribe"
    patch "withdrawal"
    member do
        get :likes
    end
    resource :relationships, only: [:create, :destroy] do
        collection do
            get 'followings' => 'relationships#followings', as: 'followings'
            get 'followers' => 'relationships#followers', as: 'followers'
        end
    end
  end
   resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
       resource :likes, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
   end
   resources :categorys, only: [:index, :edit, :create, :update, :destroy]
   resources :chats, only: [:show, :create]
   resources :notifications, only: [:index]
 end

  namespace :admin do
    root to:"customers#index"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :update, :destroy] do
     resources :comments, only: [:index, :show, :edit, :update, :destroy]
     collection do
       get 'search'
      end
    end
    resources :categorys, only: [:index, :edit, :create, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
  has_many :notifications, dependent: :destroy
  
  validates :comment, presence: true
  
  def create_notification_comment!(visiter, visited_id)
        notification = visiter.active_notifications.new(
          post_id: post_id,
          comment_id: id,
          visited_id: visited_id,
          action: 'comment'
        )
        if notification.visiter_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :customer_rooms
  has_many :chats
  has_many :rooms, through: :customer_rooms
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def likes?(post)
    likes.exists?(post: post)
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

  def follow(user_id)
     relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
   #フォロー時の通知
  def create_notification_follow!(visited_id)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",id, visited_id, 'follow'])
    if temp.blank?
      notification = active_notifications.new(
        visited_id: visited_id,
        visiter_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :post


end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}

	belongs_to :post, optional: true
  belongs_to :comment, optional: true

  # 通知
  belongs_to :visiter, class_name: 'customer', foreign_key: 'visiter_id', optional: true
	belongs_to :visited, class_name: 'customer', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 通知
  has_many :notifications, dependent: :destroy
  belongs_to :customer
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true

  scope :search_by_keyword, -> (keyword) { where("title LIKE ?", "%#{keyword}%") }

  def liked_by?(customer)
    likes&.exists?(customer_id: customer.id) if customer.present? && likes.present?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :customer_rooms
  has_many :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaigonowa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('kaigonowa.png', size: "180x50") %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            </ul>
            <ul class="navbar-nav ml-auto">
              <% if unchecked_notifications.any? %>
               <i class="fa fa-circle" style="color: gold;"></i>
              <% end %>
             <li class="nav-item">
               <%= link_to "通知", notifications_path,  class: 'btn btn-outline-dark' %>
             </li>
             <li class="nav-item">
               <%= link_to 'マイページ', customer_path(current_customer.id), class: 'btn btn-outline-dark' %>
             </li>
             <li class="nav-item">
               <%= link_to 'ユーザー', customers_path, class: 'btn btn-outline-dark' %>
             </li>
             <li class="nav-item">
               <%= link_to "投稿一覧", posts_path, class: 'btn btn-outline-dark' %>
             </li>
             <li class="nav-item">
               <%= link_to "新規投稿", new_post_path, class: 'btn btn-outline-dark' %>
             </li>
               <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark' %>
             </li>
            <% elsif admin_signed_in?%>
             <li><%= link_to ' 会員一覧', admin_customers_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' カテゴリ一覧', admin_categorys_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' 投稿一覧', admin_posts_path, class: 'btn btn-outline-dark' %>
             </li>
             <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %></li>
            <% else %>
            <li class="nav-item">
              <%= link_to "ホーム", root_path, class: 'btn btn-outline-dark' %>
            </li>
             <li class="nav-item">
             <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, class: "btn btn-outline-dark", method: :post %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", customer_session_path, class: 'btn btn-outline-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="text-right">
      <% if customer_signed_in? %>
       <%= form_tag search_posts_path, method: :get do %>
        <%= text_field_tag :keyword, params[:keyword], placeholder: "キーワードを入力してください", size: 30 %>
        <%= submit_tag "検索" %>
       <% end %>
       <% elsif admin_signed_in?%>
       <%= form_tag search_admin_posts_path, method: :get do %>
        <%= text_field_tag :keyword, params[:keyword], placeholder: "キーワードを入力してください", size: 30 %>
        <%= submit_tag "検索" %>
        <% end %>
       <% end %>
      </div>
    </header>
    <main class="mb-auto">
      <nav style="background-color: #FFFAF0;">
    <%= yield %>
    </main>
  </body>
</html>